name: Docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        version:
        - "5.0.195"
        - "6.0.85"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

      - name: Configure
      id: config
      run: |-
        NPROC=$(nproc)

        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_ENV
        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_OUTPUT

        echo "image-owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "image-name=${GITHUB_REPOSITORY#*/docker-}" >> $GITHUB_OUTPUT

    - name: Setup - Setup buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup - Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |-
          ${{ steps.config.outputs.repo-owner }}/${{ steps.config.outputs.repo-name }}
          ghcr.io/${{ steps.config.outputs.repo-owner }}/${{ steps.config.outputs.repo-name }}
        tags: |-
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.version }}

    - name: Build
      uses: docker/build-push-action@v5
      id: build
      with:
        context: .
        build-args: |
          version=${{ matrix.version }}
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
